name: Commit Signatures

on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
permissions: {}

jobs:
  signatures:
    name: Assert all commits are PGP-signed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check commit signatures
        run: bash contrib/check-signatures.sh
